### ISSUE TITLE
Enemy indexes become signed

### ISSUE THREAD

**Issue by Accumulus41** [ShiningForceCentral/SF2BattleEditor#1]
Modifying battles with enemy indexes up to 186:

Initial export created accurate battles to inputs, but, on import of an index > 127, the index imported as a negative number (134 to -122, 138 to -118, 148 to -108, etc).  And when this is exported, it takes the absolute value of the index, dropping the negative.

**Comment by wizardwhosaysni** [comment]
Fixed at last : 
https://github.com/ShiningForceCentral/SF2BattleEditor/commit/1714fff54fb95a40cf0693d548f04e3894625704

Also pushed to SF2DISASM's master branch :
https://github.com/ShiningForceCentral/SF2DISASM/commit/99d3964575d08835db8a1b1108ae89d6ef528d2a

I see that currently this is not properly propagated to target build branches because of a github action errror, I'll see what I can do.

With my apologies for the very long wait !

**Comment by wizardwhosaysni** [comment]
GitHub action issue fixed with propagation of SF2BattleEditor-1.4.5 done for build/standard branch.
Conflicts remain for build/caravan branch, will be resolved later.

I'll close this issue for now, but feel free to re-open it if there's anything wrong with this fix.
